---
- name: Conditions example 2
  hosts: all
  tasks:
    - name: Register a variable, ignore errors and continue
      ansible.builtin.command: echo "Test command"
      register: result
      ignore_errors: true
    - name: Run only if the task that registered the "result" variable fails
      debug:
        msg: "Task execution failed..."
      when: result is failed
    - name: Run only if the task that registered the "result" variable succeeds
      debug:
        msg: "Task executed successfully..."
      when: result is succeeded